= Gravitee Node Cache

== Description

The *Gravitee Node Cache* module offers the capabilities to set up a global CacheManager. This Cache manager could be then used to create Cache to store data. The type of Cache will depend on the plugin used on the plate form.

== Plugins

To define the plugin to use, you must define the following property in `gravitee.yml`:

```yaml
cache:
    type: standalone|hazelcast
```

=== Standalone
The *Standalone Plugin* is a simple cache manager based on _Caffeine_ implementation. It allows creation of an in-memory cache with a simple configuration.

==== Configuration
This plugin is enabled by default and doesn't require extra configuration.

=== Hazelcast
The *Hazelcast Plugin* is entirely relying on Hazelcast implementation. It allows creating a local in-memory cache or distributed cache using Hazelcast IMap. This is to share data across a dedicated Hazelcast cluster.

==== Configuration

The underlying Hazelcast cluster is dedicated to the cache manager. A file `${gravitee.home}/config/hazelcast-cache.xml` is expected to configure it. The path could be overridden by setting `cache.hazelcast.config-path`.

A basic example:

```xml
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-5.3.xsd">

    <cluster-name>gio-apim-distributed-cache</cluster-name>
    <network>
        <port auto-increment="true" port-count="100">5701</port>
        <join>
            <auto-detection enabled="true"/>
            <multicast enabled="false"/>
            <tcp-ip enabled="true">
                <interface>127.0.0.1</interface>
            </tcp-ip>
        </join>
    </network>
</hazelcast>
```

=== Redis

The *Redis Plugin* is entirely relying on Redis implementation. It allows creating a remote cache using Redis.

==== Configuration

All the specific configurations are located under the `cache.redis` attribute.

.Redis Standalone options
|===
|Parameter |Default |Description

|host
|localhost
|

|port
|6379
|

|password
|
|

|maxPoolSize
|6
|the maximum size of the connection pool.

|maxPoolWaiting
|24
|the maximum number of requests waiting for a connection from the pool

|poolCleanerInterval
|30000
|how often the connection pool will be cleaned. (in millis)

|poolRecycleTimeout
|18000
|how long a connection can stay unused before it is recycled during connection pool cleaning (in millis)

|maxWaitingHandlers
|2048
|how much backlog you're willing to accept
|===

.Redis Sentinel options
|===
|Parameter |Default |Description

|sentinel.nodes
|
|List of sentinels with host and port

|sentinel.master
|
|mandatory when using Sentinel

|password
|
|
|===

.Redis SSL options
|===
|Parameter |Default |Description

|ssl
|false
|

|trustAll
|true
|Default value is true for backward compatibility but keep in mind that this is not a good practice and you should set to false and configure a truststore

|hostnameVerificationAlgorithm
|NONE
|Default value is NONE for backward compatibility, supports `NONE`, `HTTPS`, `LDAPS`

|tlsProtocols
|See https://vertx.io/docs/vertx-core/java/#_configuring_tls_protocol_versions[Vert.x doc]
|List of TLS protocols to allow comma separated.

|tlsCiphers
|See https://vertx.io/docs/vertx-core/java/#_configuring_the_cipher_suite[Vert.x doc]
|List of TLS ciphers to allow comma separated.

|alpn
|false
|

|openssl
|false
|Used to rely on OpenSSL Engine instead of default JDK SSL Engine

|keystore
|
|Configuration for Mutual TLS. The keystore is used to select the client certificate to send to the backend server when connecting. See <<keystore-table>>

|truststore
|
|Configuration for the truststore. The truststore is used to validate the server’s certificate. See <<truststore-table>>
|===


[#keystore-table]
.Redis SSL keystore options (client certificate, Mutual TLS)
|===
|Parameter |Default |Description
|type
|
|Supports `jks`, `pem`, `pkcs12`

|path
|
|A path is required if certificate's type is jks or pkcs12

|password
|
|

|alias
|
|

|certificates
|
|List of certificates with cert and key. Certificates are required if keystore's type is pem
|===

[#truststore-table]
.Redis SSL truststore options
|===
|Parameter |Default |Description
|type
|
|Supports `jks`, `pem`, `pkcs12`

|path
|
|

|password
|
|

|alias
|
|
|===

```yaml
cache:
  type: redis
  redis:
    host: localhost
    port: 6379
    password: ***
    ssl: false
    #maxPoolSize: 6
    #maxPoolWaiting: 24
    #poolCleanerInterval: 30000
    #poolRecycleTimeout: 18000
    #maxWaitingHandlers: 2048
    ## Sentinel mode settings (optional)
    # sentinel:
    #   master: mymaster
    #   password: ***
    #   nodes:
    #     host: host
    #     port: 6379
    ## SSL options  (optional if ssl is false)
    #hostnameVerificationAlgorithm: NONE
    #trustAll: false
    #keystore:
    #  type: PKCS12
    #  path: /path/to/pkcs.12
    #  password: ***
    #  keyPassword: ***
    #  alias: certalias
    #truststore:
    #  type: PKCS12
    #  path: /path/to/pkcs.12
    #  password: ***
    #  alias: certalias
```

== Usage

In order to use the Cache feature, you need to inject the `CacheManager` into you component, and then use it. See JavaDoc in `io.gravitee.node.api.cache.CacheManager` for more details.
